### PR TITLE
added pr_template

### PR DESCRIPTION
**Pull request by pinak22dhir**
resolved issue #4

### CODE REVIEW

**Review by Durgesh4993 — APPROVED** [review]
Approve

**Comment by Durgesh4993** [comment]
**Stay Connected with Us:**
GitHub:https://github.com/GameSphere-MultiPlayer
LinkedIn:https://www.linkedin.com/company/gamesphere-multiplayer/

**Comment by Durgesh4993** [comment]
@Aman1-coder You can merge this PR now

**Comment by pinak22dhir** [comment]
@Durgesh4993  you will merge it , if any feedback is needed please tell

**Pull request merged**
