### PR TITLE
added icons

### PR DESCRIPTION
**Pull request by Soumya6Tiwari**
Added icons on the navbar.
Screenshot (1226)

### CODE REVIEW

**Comment by Soumya6Tiwari** [comment]
@Durgesh4993 kindly review and merge my PR.

**Comment by Durgesh4993** [comment]
@Soumya6Tiwari There are some conflicts are occured please reasolve it

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
image

**Comment by Soumya6Tiwari** [comment]
@Durgesh4993  sure I will resolve it .

**Pull request closed without merging**
